### ISSUE TITLE
GDPR: Strava's download option has moved

### ISSUE THREAD

**Issue by xsanda** [erik/derive#17]

**Comment by xsanda** [comment]
The new location is at https://www.strava.com/account, and includes photos etc as well. I'm now trying to download my own data, to see how it works

**Comment by xsanda** [comment]
108 MB: rather massive

**Comment by xsanda** [comment]
The export's activities are as before, except that their file names do not include the activity type (this is included in the activities.csv file), but it now includes photos. These are not geotagged, and don't have anything to relate them to their activities or their locations. I'm not sure how well a browser would cope with 90 MB of photos…

**Comment by xsanda** [comment]
Bug report submitted:

**Subject**: Data export function does not include location information or activity ID in photos.
**Description**: When requesting a data export, there is very little information on photos taken. The photos.csv file does not include the photograph's location or the ID of the ride it was tagged on.

**Comment by erik** [comment]
Thanks for being on top of this. Kind of annoying that the location and format of everything changed

**Comment by xsanda** [comment]
And the file formats of the activities is an absolute mess: it's a mixture of gpx, tcx and gzip’ed versions of each

**Comment by hugovk** [comment]
Yeah, the mixture is annoying, it's because the zip contains the original files that were uploaded. So I have FIT files for the activities from my GPS recorder, and GPX from the Strava app.

The earlier download only had GPX, which included Strava's "corrections", like if some elevation was clearly off. I think if you sent a GDPR request, they should still send the processed versions of your data.

**Comment by erik** [comment]
I think we can call this resolved since there's been support for `.fit`, `.fit.gz`, and `.tcx` as well, which should cover the common cases.
