### ISSUE TITLE
Support FIT files

### ISSUE THREAD

**Issue by erik** [erik/derive#19]
(gzipped or not)

My data dump from strava since the GDPR change (#17) contains `.fit.gz` files. Should look into parsing these.

**Comment by xsanda** [comment]
Would you be able to post an example of such a file?

**Comment by xsanda** [comment]
As it’s a binary file, the logic with unzipping will may need to be altered a bit, as I’m not sure how safe it will be to read binary data into a 16-bit JavaScript string. This could be done by unzipping to a closure `(isBinary: boolean) => string | UInt8Array`. Once it’s been read, easy-fit looks like the best candidate package for parsing it, but it’s not exactly stable.

**Comment by erik** [comment]
Here's a zipped up FIT file: [2365640155.fit.zip](https://github.com/erik/derive/files/2284257/2365640155.fit.zip)

**Comment by xuopled** [comment]
It's strange because when I try to load `.fit.gz` files to derive, Some of them are imported and the other ones failed: `Loaded 87, 1206 failures`

**Comment by xuopled** [comment]
In fact, I selected all my exported activities and drap and drop to derive. So I did not check all the files before. But now I understand what appened. Some of my activities are `.tcx.gz` and some other are `fit.gz`. So that is why some of my exported activities can be imported by `Derive`.  The `.tcx.gz` does work and the `fit.gz` does not work
