### ISSUE TITLE
Loading of some gpx files fails...

### ISSUE THREAD

**Issue by C-Makridis** [erik/derive#9]
Hello there,

I have a good number of gpx files, that fail to be loaded.
I did manage to load them by manually:

- Adding `<name></name>` under `<trk>` 
- Joining two traks by deleting `</trkseg></trk> <trk><trkseg> `

I'm not sure, but I think having two `<trk>` and `<trkseg>` elements in one gpx file seems to make sence.
I'm also not sure whether `<name>` for `<trk>` is mandatory or not (in which case I should open a bug report to OsmAND)

I have not faced this problem with other applications, so I thought that I should start by reporting here.
For reference, you will find attached the initial version of the sample gpx file that fails, as well as its edited version that works as expected.
[2018-01-09.zip](https://github.com/erik/derive/files/1670229/2018-01-09.zip)

Thank you very much for your time.

**Comment by erik** [comment]
Thanks for reporting @C-Makridis!

Looks like my [wild assumptions](https://github.com/erik/derive/blob/master/src/gpx.js#L12) finally came back to bite me 😄 

You're completely right that it makes sense to have more than one `<trk>` and `<trkseg>`, I just never ran into this before because my only source of data (Strava) seems to consistently use one.

Briefly looking at the schema for GPX, seems like `name` is not required either, so it wouldn't be a bug with OsmAnd.

I'll push out a fix for both of these bugs as soon as I get a chance!

**Comment by erik** [comment]
Just pushed a fix!

Thanks again for the report @C-Makridis, the two files you included now render correctly.
